import type { NewsItem } from "@/content/types";

export const newsItems: readonly NewsItem[] = [
  { id: "soundtrack-release", title: "The Complete Soundtrack Arrives August 28", summary: "David Fleming's complete score arrives today following its official SDCC announcement, setting the tone ahead of the September launch.", publishedAt: "2026-08-28", status: "official", sourceId: "story-trailer", tags: ["Soundtrack", "Latest"] },
  { id: "hands-on-roundup", title: "Two-Hour Hands-on Reveals Exploration and Progression", summary: "Approved previews cover the Team X opening, Madripoor exploration, Technique upgrades, and optional challenges. Final values still require launch verification.", publishedAt: "2026-08-13", status: "handsOn", sourceId: "playstation-hands-on", tags: ["Hands-on", "Gameplay"] },
  { id: "hardware-reveal", title: "Limited Edition Wolverine PS5 Hardware Revealed", summary: "PlayStation unveiled a limited-edition console bundle and matching accessories inspired by Logan's suit, claws, and battle damage.", publishedAt: "2026-08-11", status: "official", sourceId: "hardware-reveal", tags: ["Hardware", "PS5"] },
  { id: "story-trailer", title: "SDCC Story Trailer Reveals Deathstrike and The Hand", summary: "The latest story trailer expands the Team X mystery, confirms Lady Deathstrike and the Hand, and introduces new art and composer details.", publishedAt: "2026-07-23", status: "official", sourceId: "story-trailer", tags: ["Story", "Trailer"] },
  { id: "gameplay-reveal", title: "Extended Gameplay Locks In the September 15 Release", summary: "Insomniac's extended gameplay reveal confirms the release date and showcases Rage, Jean Grey, vehicle combat, and the Canada-to-Madripoor hunt.", publishedAt: "2026-06-02", status: "official", sourceId: "gameplay-reveal", tags: ["Gameplay", "Release date"] },
];
